### ISSUE TITLE
Support I2C devices

### ISSUE THREAD

**Issue by BrianGenisio** [rwaldron/particle-io#65]
This will be in conjunction with a VoodooSpark update as well. I'm starting work on this, but I wanted to create an issue to track questions and conversations here.

**Comment by rwaldron** [comment]
Cool. This should probably be heavily influenced by:

- https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L149-L184
- https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L405-L501

**Comment by BrianGenisio** [comment]
Yes, I agree.  I'm planning on a very similar model since the Wire library is available to the chip.  Hoping, actually, that this isn't too difficult to do.  More about testing devices on both Core and Photon.

**Comment by BrianGenisio** [comment]
I also see that the Tessel-io is doing [argument massaging](https://github.com/rwaldron/tessel-io/blob/master/lib/tessel.js#L499) to support old and new interfaces, so I plan to re-use that pattern as well.

**Comment by rwaldron** [comment]
- This: https://github.com/rwaldron/tessel-io/blob/master/lib/tessel.js#L496-L508 will be almost identical
- This: https://github.com/rwaldron/tessel-io/blob/master/lib/tessel.js#L509-L516 will be more like Firmata.js, where the request instruction is sent out and a local handler is registered. 


(and so on)

**Comment by BrianGenisio** [comment]
Cool.  That is exactly the direction I was planning on going.  Glad to get independent confirmation that I'm moving in the right direction from the spelunking I've been doing.

**Comment by rwaldron** [comment]
Looks like we did this ;)
