### ISSUE TITLE
pin normalization issue when using particle-io and oled-js

### ISSUE THREAD

**Issue by d1runberg** [rwaldron/particle-io#73]
In trying to use an SPI OLED screen with J5 / Particle-io with oled-io, I found a pin naming conflict. It seems that the normalization of pin names didnt carry over to using them in this way. I am playing with it more. 

c:\Users\....\node_modules\particle-io\lib\particle.js:458
  pinInt = (pin.replace(/A|D/, "") | 0) + offset;
                ^
TypeError: pin.replace is not a function

Code I am trying to run...

var five = require('johnny-five');
var particle = require('particle-io');
var board = new five.Board({
   io: new particle({
      host: '192.168.43.118',
      port: 48879
    })
});
    Oled = require('oled-js');

board.on('ready', function() {
  console.log('Connected to Arduino, ready.');

  var opts = {
    width: 128,
    height: 64,
    slavePin: 'A5'
  };

  var oled = new Oled(board, five, opts);
  oled.fillRect(1, 1, 10, 20, 1);
});

**Comment by IanMoritz** [comment]
Did you find a solution to this?

**Comment by rwaldron** [comment]
Released in 0.13.0
