### ISSUE TITLE
pin.replace is not a function

### ISSUE THREAD

**Issue by IanMoritz** [rwaldron/particle-io#74]
Hi--

I am running into a similar error [issue 1 ](https://github.com/rwaldron/particle-io/issues/73),  [issue 2](https://github.com/rwaldron/particle-io/issues/63). I am pretty new to this so any guidance is greatly appreciated. 

- Particle Photon Board
- Shield Shield
- Johnny Five
- Particle-io
- [Continous Servo](https://www.adafruit.com/products/2442?gclid=CjwKEAjwiru9BRDwyKmR08L3iS0SJABN8T4vnquEgYW7sRy2NYRYyFRs-UIIgjqUOHry6PUdEd1BxxoCEWvw_wcB)

Here's the script:
[
Pretty much this example](http://johnny-five.io/examples/servo-continuous/)

```
var five = require("johnny-five");
var Particle = require("particle-io");
var board = new five.Board({
  io: new Particle({
    token: "...",
    deviceId: "..."
  })
});

board.on("ready", function() {

  console.log("Use Up and Down arrows for CW and CCW respectively. Space to stop.");

  var servo = new five.Servo.Continuous(10);

  process.stdin.resume();
  process.stdin.setEncoding("utf8");
  process.stdin.setRawMode(true);

  process.stdin.on("keypress", function(ch, key) {

    if (!key) {
      return;
    }

    if (key.name === "q") {
      console.log("Quitting");
      process.exit();
    } else if (key.name === "up") {
      console.log("CW");
      servo.cw();
    } else if (key.name === "down") {
      console.log("CCW");
      servo.ccw();
    } else if (key.name === "space") {
      console.log("Stopping");
      servo.stop();
    }
  });
});

```

Here's the error:
```
1471134659325 Device(s) particle-io  
1471134661721 Connected particle-io  
1471134661821 Repl Initialized  
>> Use Up and Down arrows for CW and CCW respectively. Space to stop.
/Users/IanTMoritz/Desktop/Dash of Love/node_modules/particle-io/lib/particle.js:458
  pinInt = (pin.replace(/A|D/, "") | 0) + offset;
                ^

TypeError: pin.replace is not a function
    at Particle.pinMode (/Users/IanTMoritz/Desktop/Dash of Love/node_modules/particle-io/lib/particle.js:458:17)
    at Servo.Controllers.Standard.initialize.value (/Users/IanTMoritz/Desktop/Dash of Love/node_modules/johnny-five/lib/servo.js:59:19)
    at new Servo (/Users/IanTMoritz/Desktop/Dash of Love/node_modules/johnny-five/lib/servo.js:189:8)
    at new Servo.Continuous (/Users/IanTMoritz/Desktop/Dash of Love/node_modules/johnny-five/lib/servo.js:514:10)
    at Board.<anonymous> (/Users/IanTMoritz/Desktop/Dash of Love/bot4.js:16:15)
    at emitNone (events.js:72:20)
    at Board.emit (events.js:166:7)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

Does it have something to do with the[ mapping of the shield](https://docs.particle.io/datasheets/particle-shields/#shield-shield-pin-mapping)? 

Thanks!

**Comment by rwaldron** [comment]
> Does it have something to do with the mapping of the shield?

Probably. Johnny-Five and all of it's IO-Plugins expect the pin number as printed on the board for which is being represented (by the IO-Plugin). Based on that, and the shield's pin mapping, I believe you need to use "D5"

**Comment by rwaldron** [comment]
A bit more discussion... There is no way that Particle-io/Johnny-Five could ever possibly know that you meant  `"D5"` by the number `10`. I accepted a long time ago that there would never be a nice way to disambiguate pin numbers as they appear on all the shields in the world with what is printed on the board. So, faced with a decision, I went with the the concrete and easily reasoned: "only expect what's printed on the board".

**Comment by IanMoritz** [comment]
First off, really appreciate what you do-- particle.io / Johnny-Five is amazing!

The release fixed the problem.  I realized after the comment that I probably would have to map the shield to the photon like you mentioned. 

Thanks again!

**Comment by rwaldron** [comment]
> The release fixed the problem

That's great! Thanks again for filing the issue :)
