### ISSUE TITLE
Detect restart of photon

### ISSUE THREAD

**Issue by gsbucks** [rwaldron/particle-io#75]
Hi, I'm using the voodoospark firmware and this library to send commands from a server to a photon.

I'm curious if there's an existing way that I'm not seeing to re-initialize a Particle instance if connection with the photon is lost. A digitalRead handler will just stop being called if, for example, the photon gets restarted. As far as I can tell the Particle object's 'error' handler will also never get called in this case.

It doesn't look like the net.socket object being used is exposed anywhere, nor are its 'close' or 'error' events handled. I can get around it by pinging the photon and reconnecting if it doesn't respond, but I'd prefer responding to the socket library's events.

Everything else is working as expected, thanks for your work on these libraries!

**Comment by rwaldron** [comment]
The program running the JavaScript code must be restarted, as there is no safe/sane way to reliably restore the state if the remote Photon has cycled.
