### ISSUE TITLE
MPU6050 example not working

### ISSUE THREAD

**Issue by robtarr** [rwaldron/particle-io#76]
I tried the sample code for the MPU6050 with a Particle Photon and could not get it to work. I logged `0` for all values on start, and then never seems to fire the `change` event again.

```
1472520526381 Device(s) particle-io
1472520526767 Connected particle-io
1472520526806 Repl Initialized
>> accelerometer
  x            :  0
  y            :  0
  z            :  0
  pitch        :  0
  roll         :  0
  acceleration :  0
  inclination  :  0
  orientation  :  0
--------------------------------------
```

I am using VoodooSpark `4.0.0` and have tried with Particle-io `0.12.0` and `0.14.0`.

**Comment by rwaldron** [comment]
Thanks for filing the issue. I'm away from home until Thursday and don't have a Photon or MPU6050 with me. This is really alarming though, because I specifically used the MPU6050 during the development of I2C support in Particle-IO

@BrianGenisio do you have a spare cycle to repro this?

**Comment by rwaldron** [comment]
Looking at the list under: 

> Examples of the components that are now supported on the Particle devices in Johnny-Five include:

That's just a list of I2C things supported at the time—I will update the post

**Comment by robtarr** [comment]
Thanks for looking into it. If there is anything else that I can do to test things, please let me know.

**Comment by robtarr** [comment]
I retested it tonight, I think I must have had a loose connection between the MPU6050 and the breadboard. Everything seems to be working great!
